import type { NextPage } from "next";
import Head from "next/head";

export const getServerSideProps = async () => {
  const res = await fetch("http:localhost:3000/api/meta");
  const data = await res.json();
  return { props: { title: data.title } };
};

const Home: NextPage<{ title: string }> = ({ title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen bg-base-200">Hallo</div>
    </>
  );
};

export default Home;
